### PR TITLE
[FIX]no module found error importlib.metadata if python <3.8

### PR DESCRIPTION
**Pull request by omalbastin**

### CODE REVIEW

**Comment by omalbastin** [comment]
Issue related to https://github.com/prestapyt/prestapyt/issues/62

**Review by pedrobaeza — DISMISSED** [review]

**Comment by pedrobaeza** [comment]
`importlib_metadata` seems a bit weird to be an import though, isn't it? Are you sure this one is the correct? For which version is this working?

**Comment by omalbastin** [comment]
I have tested with python 3.6

**Comment by pedrobaeza** [comment]
But it was working previously with such version, and nobody has complaint about any problem with this.

**Comment by omalbastin** [comment]
dependency to this package were added in https://github.com/prestapyt/prestapyt/commit/df2594c0a84c26cc46bebc2dc93ab0b948fc6f2b

**Comment by pedrobaeza** [comment]
Yes, but I mean that the import was working in Python 3.6 AFAIK.

**Comment by omalbastin** [comment]
okey. it was not working in my linux distro (elementary os based on ubuntu 18.04) with python 3.6.  What I found was importlib.metadata is supported from python 3.8. Maybe im missing something

**Comment by nilshamerlinck** [comment]
Hi @omalbastin and @pedrobaeza 

I faced the same issue:
- `importlib.metadata` is part of python stdlib [since 3.8 only](https://docs.python.org/3.8/library/importlib.metadata.html)
- for older python versions, we need indeed to rely on `importlib-metadata` module

@omalbastin can you please complement your fix with:
- a comment such as "for python < 3.8" after `except:`
- a line `'importlib-metadata; python_version < "3.8",'` in https://github.com/prestapyt/prestapyt/blob/64c684b2adf44decf19f60e801fc2e280cfc8342/setup.py#L28

Thanks!

**Comment by watou** [comment]
This PR was needed to use the library on my Ubuntu 18.04 running Python 3.6.9.  Thank you @omalbastin for submitting it.  Please considering merging. 👍

**Comment by ventor-dev** [comment]
@pedrobaeza why this PR us not yet merged? It is absolutely needed to make it work both for Python 3.8 and Python <3.8

**Comment by pedrobaeza** [comment]
Nobody told me about the requested changes were done. Anyways, now it can't be merged, as there's a merge commit in the branch. Please squash all in one commit.

**Comment by ventor-dev** [comment]
@omalbastin as you original did change, could you, please, do what Pedro requested? 
So there is no need to create a new pull request

**Comment by watou** [comment]
I've just submitted #75 if that makes things easier.

**Comment by watou** [comment]
Please consider #76 unless original submitter @omalbastin  wishes otherwise.

**Comment by omalbastin** [comment]
anyone guide me how to do it?

**Comment by watou** [comment]
Your commits now constitute my PR, but if you want to use your own PR instead, you can create a new branch in your fork:
```
git checkout -b metadata_fix   # for example
```
Add your two previous commits:
```
git cherry-pick -x 3d62816027d71edc3d1054a6ebe091b14cdc0360
git cherry-pick -x 72dbe21c32d10fe0cf39b4bbe9d7582582365b47
```
Push your branch back to github:
```
git push origin metadata_fix
```
Create a new PR following the PR rules for this repo.
Hopefully that gets it done!  Or they can merge #76 and it's equivalent.  Whichever, as long as something get merged!

**Comment by ventor-dev** [comment]
@omalbastin will you be ok if instead of your PR, this one will be used https://github.com/prestapyt/prestapyt/pull/76
Latest was created by @watou using above method

**Comment by omalbastin** [comment]
@ventor-dev sure. no problem. i just need the issue to be fixed

**Pull request closed without merging**
