### PR TITLE
PEP 632 -- Deprecate distutils module

### PR DESCRIPTION
**Pull request by Dymirt**
Python 3.10 Fix Deprecate distutils module issue #70

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is `packaging` available for all Python versions?

**Comment by Dymirt** [comment]
`packaging` Requires: Python >=3.6

**Comment by pedrobaeza** [comment]
Then you should provide a path for both Python 2.x/3.x, doing conditional imports, as this library is still compatible with lower versions. Maybe a `try`/`except ImportError` clause may work

**Comment by Dymirt** [comment]
Thank you for advice, latest commit use conditional imports.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
