### PR TITLE
Bump the version to 0.9.1

### PR DESCRIPTION
**Pull request by flotho**
This PR https://github.com/prestapyt/prestapyt/pull/51 add some great functionalities.

Yet the version hasn't been upgraded so that pip install doesn't inform us about the correct and latest version available

### CODE REVIEW

**Comment by flotho** [comment]
ping @qtheuret , @pedrobaeza

**Comment by pedrobaeza** [comment]
Are you sure changing this will be reflected in pypi. I think pypi publication is not yet implemented.

**Comment by flotho** [comment]
So what  is the process to publisy on pypi because from now, using pip install prestapyt -U provides 0.9.0 version

**Comment by pedrobaeza** [comment]
We never install from pypi. Use:
```
pip install --ignore-installed git+https://github.com/prestapyt/prestapyt.git@master
```
for getting always latest available source code.
Any way, the proper way is to setup an automatic deployment when doing releases on GitHub, but I don't have time now for setting this up. It still requires a bump of the version in code + doing the release.

**Comment by flotho** [comment]
@pedrobaeza , great thanks for the clear explanation, as sual !

**Comment by flotho** [comment]
Hi @pedrobaeza ,

I've updated the README.md with your latest comments so that everyone will be able to check that the latest release from this repo could be different from the pypi's one.

Let me know if it's sufficient for merging this PR

**Comment by flotho** [comment]
ping @qtheuret

**Pull request merged**
