### PR TITLE
Use requests instead of httplib2

### PR DESCRIPTION
**Pull request by guewen**
* Allow to pass a custom requests.Session when instanciating a client
* The exception contains more info about the original error
* Using requests allows for instance, to use
  https://github.com/kevin1024/vcrpy or https://github.com/sigmavirus24/betamax
* The 'debug' flag do no longer print anything, it only sends the debug
  option to PrestaShop. If you want to print debug logs, you need to
  configure the logging module (http://docs.python-requests.org/en/master/api/#api-changes)
* The user-agent is now the
* Finally added the `partial_add` and `partial_edit` that I wrote years ago
* The edit function does not longer need the resource id, which is
  useless

Warning, this is a breaking change, but which is necessary.

Courtesy to Akretion
(@bealdav,@sebastienbeau,@alexis-via,@bguillot,@arthru) and
@leblanc-simon for the first integration with a previous version of
requests in https://github.com/prestapyt/prestapyt/pull/15/

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@sergio-teruel, please try this modification in our installations to see if it works correctly

**Comment by sergio-teruel** [comment]
Yes, of course, i will test it.

**Comment by simahawk** [comment]
@sergio-teruel any outcome? :)

**Comment by sergio-teruel** [comment]
All Ok.. :+1:

**Pull request merged**
